--Chiffre d'affaire total
SELECT
SUM(MONTANT_VENTE) AS MONTANT_VENTE_TOTAL
FROM FAIT_VENTES

-- Ventes par produits
SELECT 
    NOM_PRODUIT,
    SUM(MONTANT_VENTE) AS MONTANT_VENTE
FROM FAIT_VENTES 
INNER JOIN DIM_PRODUITS 
USING(ID_REFERENCE_PRODUIT)
GROUP BY NOM_PRODUIT

-- Ventes par region
SELECT 
    dm.REGION,
    COUNT(*) as nombre_ventes,
    SUM(fv.MONTANT_VENTE) as ca_total,
    AVG(fv.MONTANT_VENTE) as panier_moyen
FROM FAIT_VENTES fv
JOIN DIM_MAGASINS dm ON fv.ID_MAGASIN = dm.ID_MAGASIN
GROUP BY dm.REGION
ORDER BY ca_total DESC
